apiVersion: batch/v1
kind: CronJob
metadata:
  name: clearsessions-cronjob
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: weffy/django_app:latest
            envFrom:
              - secretRef:
                  name: django-secret
            command:
            - python3
            - manage.py
            - clearsessions
          restartPolicy: OnFailure
